/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.parser;

import ivar.grammar.node.*;
import ivar.grammar.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTApplicationKeyword(@SuppressWarnings("unused") TApplicationKeyword node)
    {
        this.index = 0;
    }

    @Override
    public void caseTCrudCreateKeyword(@SuppressWarnings("unused") TCrudCreateKeyword node)
    {
        this.index = 1;
    }

    @Override
    public void caseTCrudReadKeyword(@SuppressWarnings("unused") TCrudReadKeyword node)
    {
        this.index = 2;
    }

    @Override
    public void caseTCrudUpdateKeyword(@SuppressWarnings("unused") TCrudUpdateKeyword node)
    {
        this.index = 3;
    }

    @Override
    public void caseTCrudDeleteKeyword(@SuppressWarnings("unused") TCrudDeleteKeyword node)
    {
        this.index = 4;
    }

    @Override
    public void caseTDataKeyword(@SuppressWarnings("unused") TDataKeyword node)
    {
        this.index = 5;
    }

    @Override
    public void caseTDataModifierDefaultKeyword(@SuppressWarnings("unused") TDataModifierDefaultKeyword node)
    {
        this.index = 6;
    }

    @Override
    public void caseTImportKeyword(@SuppressWarnings("unused") TImportKeyword node)
    {
        this.index = 7;
    }

    @Override
    public void caseTRolesKeyword(@SuppressWarnings("unused") TRolesKeyword node)
    {
        this.index = 8;
    }

    @Override
    public void caseTRoleModifierAllow(@SuppressWarnings("unused") TRoleModifierAllow node)
    {
        this.index = 9;
    }

    @Override
    public void caseTRoleModifierDeny(@SuppressWarnings("unused") TRoleModifierDeny node)
    {
        this.index = 10;
    }

    @Override
    public void caseTScenarioKeyword(@SuppressWarnings("unused") TScenarioKeyword node)
    {
        this.index = 11;
    }

    @Override
    public void caseTLang(@SuppressWarnings("unused") TLang node)
    {
        this.index = 12;
    }

    @Override
    public void caseTAmountTypeKeyword(@SuppressWarnings("unused") TAmountTypeKeyword node)
    {
        this.index = 13;
    }

    @Override
    public void caseTBooleanTypeKeyword(@SuppressWarnings("unused") TBooleanTypeKeyword node)
    {
        this.index = 14;
    }

    @Override
    public void caseTDateTypeKeyword(@SuppressWarnings("unused") TDateTypeKeyword node)
    {
        this.index = 15;
    }

    @Override
    public void caseTDatetimeTypeKeyword(@SuppressWarnings("unused") TDatetimeTypeKeyword node)
    {
        this.index = 16;
    }

    @Override
    public void caseTFileTypeKeyword(@SuppressWarnings("unused") TFileTypeKeyword node)
    {
        this.index = 17;
    }

    @Override
    public void caseTFormatedtextTypeKeyword(@SuppressWarnings("unused") TFormatedtextTypeKeyword node)
    {
        this.index = 18;
    }

    @Override
    public void caseTImageTypeKeyword(@SuppressWarnings("unused") TImageTypeKeyword node)
    {
        this.index = 19;
    }

    @Override
    public void caseTIntegerTypeKeyword(@SuppressWarnings("unused") TIntegerTypeKeyword node)
    {
        this.index = 20;
    }

    @Override
    public void caseTMultitextTypeKeyword(@SuppressWarnings("unused") TMultitextTypeKeyword node)
    {
        this.index = 21;
    }

    @Override
    public void caseTNumberTypeKeyword(@SuppressWarnings("unused") TNumberTypeKeyword node)
    {
        this.index = 22;
    }

    @Override
    public void caseTPasswordTypeKeyword(@SuppressWarnings("unused") TPasswordTypeKeyword node)
    {
        this.index = 23;
    }

    @Override
    public void caseTPercentileTypeKeyword(@SuppressWarnings("unused") TPercentileTypeKeyword node)
    {
        this.index = 24;
    }

    @Override
    public void caseTRealTypeKeyword(@SuppressWarnings("unused") TRealTypeKeyword node)
    {
        this.index = 25;
    }

    @Override
    public void caseTTextTypeKeyword(@SuppressWarnings("unused") TTextTypeKeyword node)
    {
        this.index = 26;
    }

    @Override
    public void caseTTimeTypeKeyword(@SuppressWarnings("unused") TTimeTypeKeyword node)
    {
        this.index = 27;
    }

    @Override
    public void caseTIntegerLiteral(@SuppressWarnings("unused") TIntegerLiteral node)
    {
        this.index = 28;
    }

    @Override
    public void caseTStringLiteral(@SuppressWarnings("unused") TStringLiteral node)
    {
        this.index = 29;
    }

    @Override
    public void caseTIdentifier(@SuppressWarnings("unused") TIdentifier node)
    {
        this.index = 30;
    }

    @Override
    public void caseTLBrc(@SuppressWarnings("unused") TLBrc node)
    {
        this.index = 31;
    }

    @Override
    public void caseTRBrc(@SuppressWarnings("unused") TRBrc node)
    {
        this.index = 32;
    }

    @Override
    public void caseTSemi(@SuppressWarnings("unused") TSemi node)
    {
        this.index = 33;
    }

    @Override
    public void caseTDotdot(@SuppressWarnings("unused") TDotdot node)
    {
        this.index = 34;
    }

    @Override
    public void caseTDotdotstar(@SuppressWarnings("unused") TDotdotstar node)
    {
        this.index = 35;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 36;
    }

    @Override
    public void caseTStar(@SuppressWarnings("unused") TStar node)
    {
        this.index = 37;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 38;
    }
}
