/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AAmountIvarStepType extends PIvarStepType
{
    private TAmountTypeKeyword _amountTypeKeyword_;

    public AAmountIvarStepType()
    {
        // Constructor
    }

    public AAmountIvarStepType(
        @SuppressWarnings("hiding") TAmountTypeKeyword _amountTypeKeyword_)
    {
        // Constructor
        setAmountTypeKeyword(_amountTypeKeyword_);

    }

    @Override
    public Object clone()
    {
        return new AAmountIvarStepType(
            cloneNode(this._amountTypeKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAmountIvarStepType(this);
    }

    public TAmountTypeKeyword getAmountTypeKeyword()
    {
        return this._amountTypeKeyword_;
    }

    public void setAmountTypeKeyword(TAmountTypeKeyword node)
    {
        if(this._amountTypeKeyword_ != null)
        {
            this._amountTypeKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._amountTypeKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._amountTypeKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._amountTypeKeyword_ == child)
        {
            this._amountTypeKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._amountTypeKeyword_ == oldChild)
        {
            setAmountTypeKeyword((TAmountTypeKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
