/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ABooleanIvarStepType extends PIvarStepType
{
    private TBooleanTypeKeyword _booleanTypeKeyword_;

    public ABooleanIvarStepType()
    {
        // Constructor
    }

    public ABooleanIvarStepType(
        @SuppressWarnings("hiding") TBooleanTypeKeyword _booleanTypeKeyword_)
    {
        // Constructor
        setBooleanTypeKeyword(_booleanTypeKeyword_);

    }

    @Override
    public Object clone()
    {
        return new ABooleanIvarStepType(
            cloneNode(this._booleanTypeKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleanIvarStepType(this);
    }

    public TBooleanTypeKeyword getBooleanTypeKeyword()
    {
        return this._booleanTypeKeyword_;
    }

    public void setBooleanTypeKeyword(TBooleanTypeKeyword node)
    {
        if(this._booleanTypeKeyword_ != null)
        {
            this._booleanTypeKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._booleanTypeKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._booleanTypeKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._booleanTypeKeyword_ == child)
        {
            this._booleanTypeKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._booleanTypeKeyword_ == oldChild)
        {
            setBooleanTypeKeyword((TBooleanTypeKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
