/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ACompleteScenarioDeclarationScenarioDeclaration extends PScenarioDeclaration
{
    private PCompleteScenarioDeclaration _completeScenarioDeclaration_;

    public ACompleteScenarioDeclarationScenarioDeclaration()
    {
        // Constructor
    }

    public ACompleteScenarioDeclarationScenarioDeclaration(
        @SuppressWarnings("hiding") PCompleteScenarioDeclaration _completeScenarioDeclaration_)
    {
        // Constructor
        setCompleteScenarioDeclaration(_completeScenarioDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new ACompleteScenarioDeclarationScenarioDeclaration(
            cloneNode(this._completeScenarioDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompleteScenarioDeclarationScenarioDeclaration(this);
    }

    public PCompleteScenarioDeclaration getCompleteScenarioDeclaration()
    {
        return this._completeScenarioDeclaration_;
    }

    public void setCompleteScenarioDeclaration(PCompleteScenarioDeclaration node)
    {
        if(this._completeScenarioDeclaration_ != null)
        {
            this._completeScenarioDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._completeScenarioDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._completeScenarioDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._completeScenarioDeclaration_ == child)
        {
            this._completeScenarioDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._completeScenarioDeclaration_ == oldChild)
        {
            setCompleteScenarioDeclaration((PCompleteScenarioDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
