/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ACompleteStepScenarioElement extends PScenarioElement
{
    private PCompleteStepDeclaration _completeStepDeclaration_;

    public ACompleteStepScenarioElement()
    {
        // Constructor
    }

    public ACompleteStepScenarioElement(
        @SuppressWarnings("hiding") PCompleteStepDeclaration _completeStepDeclaration_)
    {
        // Constructor
        setCompleteStepDeclaration(_completeStepDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new ACompleteStepScenarioElement(
            cloneNode(this._completeStepDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompleteStepScenarioElement(this);
    }

    public PCompleteStepDeclaration getCompleteStepDeclaration()
    {
        return this._completeStepDeclaration_;
    }

    public void setCompleteStepDeclaration(PCompleteStepDeclaration node)
    {
        if(this._completeStepDeclaration_ != null)
        {
            this._completeStepDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._completeStepDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._completeStepDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._completeStepDeclaration_ == child)
        {
            this._completeStepDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._completeStepDeclaration_ == oldChild)
        {
            setCompleteStepDeclaration((PCompleteStepDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
