/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ACreateCrudModifier extends PCrudModifier
{
    private TCrudCreateKeyword _crudCreateKeyword_;

    public ACreateCrudModifier()
    {
        // Constructor
    }

    public ACreateCrudModifier(
        @SuppressWarnings("hiding") TCrudCreateKeyword _crudCreateKeyword_)
    {
        // Constructor
        setCrudCreateKeyword(_crudCreateKeyword_);

    }

    @Override
    public Object clone()
    {
        return new ACreateCrudModifier(
            cloneNode(this._crudCreateKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACreateCrudModifier(this);
    }

    public TCrudCreateKeyword getCrudCreateKeyword()
    {
        return this._crudCreateKeyword_;
    }

    public void setCrudCreateKeyword(TCrudCreateKeyword node)
    {
        if(this._crudCreateKeyword_ != null)
        {
            this._crudCreateKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._crudCreateKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._crudCreateKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._crudCreateKeyword_ == child)
        {
            this._crudCreateKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._crudCreateKeyword_ == oldChild)
        {
            setCrudCreateKeyword((TCrudCreateKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
