/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ACustomStepTypeStepType extends PStepType
{
    private PCustomStepType _customStepType_;

    public ACustomStepTypeStepType()
    {
        // Constructor
    }

    public ACustomStepTypeStepType(
        @SuppressWarnings("hiding") PCustomStepType _customStepType_)
    {
        // Constructor
        setCustomStepType(_customStepType_);

    }

    @Override
    public Object clone()
    {
        return new ACustomStepTypeStepType(
            cloneNode(this._customStepType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACustomStepTypeStepType(this);
    }

    public PCustomStepType getCustomStepType()
    {
        return this._customStepType_;
    }

    public void setCustomStepType(PCustomStepType node)
    {
        if(this._customStepType_ != null)
        {
            this._customStepType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._customStepType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._customStepType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._customStepType_ == child)
        {
            this._customStepType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._customStepType_ == oldChild)
        {
            setCustomStepType((PCustomStepType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
