/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ADateIvarStepType extends PIvarStepType
{
    private TDateTypeKeyword _dateTypeKeyword_;

    public ADateIvarStepType()
    {
        // Constructor
    }

    public ADateIvarStepType(
        @SuppressWarnings("hiding") TDateTypeKeyword _dateTypeKeyword_)
    {
        // Constructor
        setDateTypeKeyword(_dateTypeKeyword_);

    }

    @Override
    public Object clone()
    {
        return new ADateIvarStepType(
            cloneNode(this._dateTypeKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADateIvarStepType(this);
    }

    public TDateTypeKeyword getDateTypeKeyword()
    {
        return this._dateTypeKeyword_;
    }

    public void setDateTypeKeyword(TDateTypeKeyword node)
    {
        if(this._dateTypeKeyword_ != null)
        {
            this._dateTypeKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dateTypeKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dateTypeKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dateTypeKeyword_ == child)
        {
            this._dateTypeKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dateTypeKeyword_ == oldChild)
        {
            setDateTypeKeyword((TDateTypeKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
