/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ADatetimeIvarStepType extends PIvarStepType
{
    private TDatetimeTypeKeyword _datetimeTypeKeyword_;

    public ADatetimeIvarStepType()
    {
        // Constructor
    }

    public ADatetimeIvarStepType(
        @SuppressWarnings("hiding") TDatetimeTypeKeyword _datetimeTypeKeyword_)
    {
        // Constructor
        setDatetimeTypeKeyword(_datetimeTypeKeyword_);

    }

    @Override
    public Object clone()
    {
        return new ADatetimeIvarStepType(
            cloneNode(this._datetimeTypeKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADatetimeIvarStepType(this);
    }

    public TDatetimeTypeKeyword getDatetimeTypeKeyword()
    {
        return this._datetimeTypeKeyword_;
    }

    public void setDatetimeTypeKeyword(TDatetimeTypeKeyword node)
    {
        if(this._datetimeTypeKeyword_ != null)
        {
            this._datetimeTypeKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._datetimeTypeKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._datetimeTypeKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._datetimeTypeKeyword_ == child)
        {
            this._datetimeTypeKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._datetimeTypeKeyword_ == oldChild)
        {
            setDatetimeTypeKeyword((TDatetimeTypeKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
