/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ADeclarationScenarioDeclarations extends PScenarioDeclarations
{
    private PScenarioDeclaration _scenarioDeclaration_;

    public ADeclarationScenarioDeclarations()
    {
        // Constructor
    }

    public ADeclarationScenarioDeclarations(
        @SuppressWarnings("hiding") PScenarioDeclaration _scenarioDeclaration_)
    {
        // Constructor
        setScenarioDeclaration(_scenarioDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new ADeclarationScenarioDeclarations(
            cloneNode(this._scenarioDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclarationScenarioDeclarations(this);
    }

    public PScenarioDeclaration getScenarioDeclaration()
    {
        return this._scenarioDeclaration_;
    }

    public void setScenarioDeclaration(PScenarioDeclaration node)
    {
        if(this._scenarioDeclaration_ != null)
        {
            this._scenarioDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._scenarioDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._scenarioDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._scenarioDeclaration_ == child)
        {
            this._scenarioDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._scenarioDeclaration_ == oldChild)
        {
            setScenarioDeclaration((PScenarioDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
