/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ADenyRoleModifier extends PRoleModifier
{
    private TRoleModifierDeny _roleModifierDeny_;

    public ADenyRoleModifier()
    {
        // Constructor
    }

    public ADenyRoleModifier(
        @SuppressWarnings("hiding") TRoleModifierDeny _roleModifierDeny_)
    {
        // Constructor
        setRoleModifierDeny(_roleModifierDeny_);

    }

    @Override
    public Object clone()
    {
        return new ADenyRoleModifier(
            cloneNode(this._roleModifierDeny_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADenyRoleModifier(this);
    }

    public TRoleModifierDeny getRoleModifierDeny()
    {
        return this._roleModifierDeny_;
    }

    public void setRoleModifierDeny(TRoleModifierDeny node)
    {
        if(this._roleModifierDeny_ != null)
        {
            this._roleModifierDeny_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._roleModifierDeny_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._roleModifierDeny_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._roleModifierDeny_ == child)
        {
            this._roleModifierDeny_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._roleModifierDeny_ == oldChild)
        {
            setRoleModifierDeny((TRoleModifierDeny) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
