/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AElementScenarioElements extends PScenarioElements
{
    private PScenarioElement _scenarioElement_;

    public AElementScenarioElements()
    {
        // Constructor
    }

    public AElementScenarioElements(
        @SuppressWarnings("hiding") PScenarioElement _scenarioElement_)
    {
        // Constructor
        setScenarioElement(_scenarioElement_);

    }

    @Override
    public Object clone()
    {
        return new AElementScenarioElements(
            cloneNode(this._scenarioElement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElementScenarioElements(this);
    }

    public PScenarioElement getScenarioElement()
    {
        return this._scenarioElement_;
    }

    public void setScenarioElement(PScenarioElement node)
    {
        if(this._scenarioElement_ != null)
        {
            this._scenarioElement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._scenarioElement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._scenarioElement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._scenarioElement_ == child)
        {
            this._scenarioElement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._scenarioElement_ == oldChild)
        {
            setScenarioElement((PScenarioElement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
