/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AElementsScenarioElements extends PScenarioElements
{
    private PScenarioElements _scenarioElements_;
    private PScenarioElement _scenarioElement_;

    public AElementsScenarioElements()
    {
        // Constructor
    }

    public AElementsScenarioElements(
        @SuppressWarnings("hiding") PScenarioElements _scenarioElements_,
        @SuppressWarnings("hiding") PScenarioElement _scenarioElement_)
    {
        // Constructor
        setScenarioElements(_scenarioElements_);

        setScenarioElement(_scenarioElement_);

    }

    @Override
    public Object clone()
    {
        return new AElementsScenarioElements(
            cloneNode(this._scenarioElements_),
            cloneNode(this._scenarioElement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElementsScenarioElements(this);
    }

    public PScenarioElements getScenarioElements()
    {
        return this._scenarioElements_;
    }

    public void setScenarioElements(PScenarioElements node)
    {
        if(this._scenarioElements_ != null)
        {
            this._scenarioElements_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._scenarioElements_ = node;
    }

    public PScenarioElement getScenarioElement()
    {
        return this._scenarioElement_;
    }

    public void setScenarioElement(PScenarioElement node)
    {
        if(this._scenarioElement_ != null)
        {
            this._scenarioElement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._scenarioElement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._scenarioElements_)
            + toString(this._scenarioElement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._scenarioElements_ == child)
        {
            this._scenarioElements_ = null;
            return;
        }

        if(this._scenarioElement_ == child)
        {
            this._scenarioElement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._scenarioElements_ == oldChild)
        {
            setScenarioElements((PScenarioElements) newChild);
            return;
        }

        if(this._scenarioElement_ == oldChild)
        {
            setScenarioElement((PScenarioElement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
