/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AFileIvarStepType extends PIvarStepType
{
    private TFileTypeKeyword _fileTypeKeyword_;

    public AFileIvarStepType()
    {
        // Constructor
    }

    public AFileIvarStepType(
        @SuppressWarnings("hiding") TFileTypeKeyword _fileTypeKeyword_)
    {
        // Constructor
        setFileTypeKeyword(_fileTypeKeyword_);

    }

    @Override
    public Object clone()
    {
        return new AFileIvarStepType(
            cloneNode(this._fileTypeKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFileIvarStepType(this);
    }

    public TFileTypeKeyword getFileTypeKeyword()
    {
        return this._fileTypeKeyword_;
    }

    public void setFileTypeKeyword(TFileTypeKeyword node)
    {
        if(this._fileTypeKeyword_ != null)
        {
            this._fileTypeKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fileTypeKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fileTypeKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fileTypeKeyword_ == child)
        {
            this._fileTypeKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fileTypeKeyword_ == oldChild)
        {
            setFileTypeKeyword((TFileTypeKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
