/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AFormatedtextIvarStepType extends PIvarStepType
{
    private TFormatedtextTypeKeyword _formatedtextTypeKeyword_;

    public AFormatedtextIvarStepType()
    {
        // Constructor
    }

    public AFormatedtextIvarStepType(
        @SuppressWarnings("hiding") TFormatedtextTypeKeyword _formatedtextTypeKeyword_)
    {
        // Constructor
        setFormatedtextTypeKeyword(_formatedtextTypeKeyword_);

    }

    @Override
    public Object clone()
    {
        return new AFormatedtextIvarStepType(
            cloneNode(this._formatedtextTypeKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFormatedtextIvarStepType(this);
    }

    public TFormatedtextTypeKeyword getFormatedtextTypeKeyword()
    {
        return this._formatedtextTypeKeyword_;
    }

    public void setFormatedtextTypeKeyword(TFormatedtextTypeKeyword node)
    {
        if(this._formatedtextTypeKeyword_ != null)
        {
            this._formatedtextTypeKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._formatedtextTypeKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._formatedtextTypeKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._formatedtextTypeKeyword_ == child)
        {
            this._formatedtextTypeKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._formatedtextTypeKeyword_ == oldChild)
        {
            setFormatedtextTypeKeyword((TFormatedtextTypeKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
