/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AImageIvarStepType extends PIvarStepType
{
    private TImageTypeKeyword _imageTypeKeyword_;

    public AImageIvarStepType()
    {
        // Constructor
    }

    public AImageIvarStepType(
        @SuppressWarnings("hiding") TImageTypeKeyword _imageTypeKeyword_)
    {
        // Constructor
        setImageTypeKeyword(_imageTypeKeyword_);

    }

    @Override
    public Object clone()
    {
        return new AImageIvarStepType(
            cloneNode(this._imageTypeKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAImageIvarStepType(this);
    }

    public TImageTypeKeyword getImageTypeKeyword()
    {
        return this._imageTypeKeyword_;
    }

    public void setImageTypeKeyword(TImageTypeKeyword node)
    {
        if(this._imageTypeKeyword_ != null)
        {
            this._imageTypeKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._imageTypeKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._imageTypeKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._imageTypeKeyword_ == child)
        {
            this._imageTypeKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._imageTypeKeyword_ == oldChild)
        {
            setImageTypeKeyword((TImageTypeKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
