/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AIvarStepTypeStepType extends PStepType
{
    private PIvarStepType _ivarStepType_;

    public AIvarStepTypeStepType()
    {
        // Constructor
    }

    public AIvarStepTypeStepType(
        @SuppressWarnings("hiding") PIvarStepType _ivarStepType_)
    {
        // Constructor
        setIvarStepType(_ivarStepType_);

    }

    @Override
    public Object clone()
    {
        return new AIvarStepTypeStepType(
            cloneNode(this._ivarStepType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIvarStepTypeStepType(this);
    }

    public PIvarStepType getIvarStepType()
    {
        return this._ivarStepType_;
    }

    public void setIvarStepType(PIvarStepType node)
    {
        if(this._ivarStepType_ != null)
        {
            this._ivarStepType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ivarStepType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ivarStepType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ivarStepType_ == child)
        {
            this._ivarStepType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ivarStepType_ == oldChild)
        {
            setIvarStepType((PIvarStepType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
