/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AMultitextIvarStepType extends PIvarStepType
{
    private TMultitextTypeKeyword _multitextTypeKeyword_;

    public AMultitextIvarStepType()
    {
        // Constructor
    }

    public AMultitextIvarStepType(
        @SuppressWarnings("hiding") TMultitextTypeKeyword _multitextTypeKeyword_)
    {
        // Constructor
        setMultitextTypeKeyword(_multitextTypeKeyword_);

    }

    @Override
    public Object clone()
    {
        return new AMultitextIvarStepType(
            cloneNode(this._multitextTypeKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultitextIvarStepType(this);
    }

    public TMultitextTypeKeyword getMultitextTypeKeyword()
    {
        return this._multitextTypeKeyword_;
    }

    public void setMultitextTypeKeyword(TMultitextTypeKeyword node)
    {
        if(this._multitextTypeKeyword_ != null)
        {
            this._multitextTypeKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multitextTypeKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multitextTypeKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multitextTypeKeyword_ == child)
        {
            this._multitextTypeKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multitextTypeKeyword_ == oldChild)
        {
            setMultitextTypeKeyword((TMultitextTypeKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
