/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class APasswordIvarStepType extends PIvarStepType
{
    private TPasswordTypeKeyword _passwordTypeKeyword_;

    public APasswordIvarStepType()
    {
        // Constructor
    }

    public APasswordIvarStepType(
        @SuppressWarnings("hiding") TPasswordTypeKeyword _passwordTypeKeyword_)
    {
        // Constructor
        setPasswordTypeKeyword(_passwordTypeKeyword_);

    }

    @Override
    public Object clone()
    {
        return new APasswordIvarStepType(
            cloneNode(this._passwordTypeKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPasswordIvarStepType(this);
    }

    public TPasswordTypeKeyword getPasswordTypeKeyword()
    {
        return this._passwordTypeKeyword_;
    }

    public void setPasswordTypeKeyword(TPasswordTypeKeyword node)
    {
        if(this._passwordTypeKeyword_ != null)
        {
            this._passwordTypeKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._passwordTypeKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._passwordTypeKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._passwordTypeKeyword_ == child)
        {
            this._passwordTypeKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._passwordTypeKeyword_ == oldChild)
        {
            setPasswordTypeKeyword((TPasswordTypeKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
