/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class APercentileIvarStepType extends PIvarStepType
{
    private TPercentileTypeKeyword _percentileTypeKeyword_;

    public APercentileIvarStepType()
    {
        // Constructor
    }

    public APercentileIvarStepType(
        @SuppressWarnings("hiding") TPercentileTypeKeyword _percentileTypeKeyword_)
    {
        // Constructor
        setPercentileTypeKeyword(_percentileTypeKeyword_);

    }

    @Override
    public Object clone()
    {
        return new APercentileIvarStepType(
            cloneNode(this._percentileTypeKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPercentileIvarStepType(this);
    }

    public TPercentileTypeKeyword getPercentileTypeKeyword()
    {
        return this._percentileTypeKeyword_;
    }

    public void setPercentileTypeKeyword(TPercentileTypeKeyword node)
    {
        if(this._percentileTypeKeyword_ != null)
        {
            this._percentileTypeKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._percentileTypeKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._percentileTypeKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._percentileTypeKeyword_ == child)
        {
            this._percentileTypeKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._percentileTypeKeyword_ == oldChild)
        {
            setPercentileTypeKeyword((TPercentileTypeKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
