/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AReadCrudModifier extends PCrudModifier
{
    private TCrudReadKeyword _crudReadKeyword_;

    public AReadCrudModifier()
    {
        // Constructor
    }

    public AReadCrudModifier(
        @SuppressWarnings("hiding") TCrudReadKeyword _crudReadKeyword_)
    {
        // Constructor
        setCrudReadKeyword(_crudReadKeyword_);

    }

    @Override
    public Object clone()
    {
        return new AReadCrudModifier(
            cloneNode(this._crudReadKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReadCrudModifier(this);
    }

    public TCrudReadKeyword getCrudReadKeyword()
    {
        return this._crudReadKeyword_;
    }

    public void setCrudReadKeyword(TCrudReadKeyword node)
    {
        if(this._crudReadKeyword_ != null)
        {
            this._crudReadKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._crudReadKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._crudReadKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._crudReadKeyword_ == child)
        {
            this._crudReadKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._crudReadKeyword_ == oldChild)
        {
            setCrudReadKeyword((TCrudReadKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
