/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ARolesDeclaration extends PRolesDeclaration
{
    private TRolesKeyword _rolesKeyword_;
    private TLBrc _lBrc_;
    private PRoleList _roleList_;
    private TRBrc _rBrc_;

    public ARolesDeclaration()
    {
        // Constructor
    }

    public ARolesDeclaration(
        @SuppressWarnings("hiding") TRolesKeyword _rolesKeyword_,
        @SuppressWarnings("hiding") TLBrc _lBrc_,
        @SuppressWarnings("hiding") PRoleList _roleList_,
        @SuppressWarnings("hiding") TRBrc _rBrc_)
    {
        // Constructor
        setRolesKeyword(_rolesKeyword_);

        setLBrc(_lBrc_);

        setRoleList(_roleList_);

        setRBrc(_rBrc_);

    }

    @Override
    public Object clone()
    {
        return new ARolesDeclaration(
            cloneNode(this._rolesKeyword_),
            cloneNode(this._lBrc_),
            cloneNode(this._roleList_),
            cloneNode(this._rBrc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARolesDeclaration(this);
    }

    public TRolesKeyword getRolesKeyword()
    {
        return this._rolesKeyword_;
    }

    public void setRolesKeyword(TRolesKeyword node)
    {
        if(this._rolesKeyword_ != null)
        {
            this._rolesKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rolesKeyword_ = node;
    }

    public TLBrc getLBrc()
    {
        return this._lBrc_;
    }

    public void setLBrc(TLBrc node)
    {
        if(this._lBrc_ != null)
        {
            this._lBrc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBrc_ = node;
    }

    public PRoleList getRoleList()
    {
        return this._roleList_;
    }

    public void setRoleList(PRoleList node)
    {
        if(this._roleList_ != null)
        {
            this._roleList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._roleList_ = node;
    }

    public TRBrc getRBrc()
    {
        return this._rBrc_;
    }

    public void setRBrc(TRBrc node)
    {
        if(this._rBrc_ != null)
        {
            this._rBrc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBrc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rolesKeyword_)
            + toString(this._lBrc_)
            + toString(this._roleList_)
            + toString(this._rBrc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rolesKeyword_ == child)
        {
            this._rolesKeyword_ = null;
            return;
        }

        if(this._lBrc_ == child)
        {
            this._lBrc_ = null;
            return;
        }

        if(this._roleList_ == child)
        {
            this._roleList_ = null;
            return;
        }

        if(this._rBrc_ == child)
        {
            this._rBrc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rolesKeyword_ == oldChild)
        {
            setRolesKeyword((TRolesKeyword) newChild);
            return;
        }

        if(this._lBrc_ == oldChild)
        {
            setLBrc((TLBrc) newChild);
            return;
        }

        if(this._roleList_ == oldChild)
        {
            setRoleList((PRoleList) newChild);
            return;
        }

        if(this._rBrc_ == oldChild)
        {
            setRBrc((TRBrc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
