/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AScenarioRolesDeclarationScenarioElement extends PScenarioElement
{
    private PRolesDeclaration _rolesDeclaration_;

    public AScenarioRolesDeclarationScenarioElement()
    {
        // Constructor
    }

    public AScenarioRolesDeclarationScenarioElement(
        @SuppressWarnings("hiding") PRolesDeclaration _rolesDeclaration_)
    {
        // Constructor
        setRolesDeclaration(_rolesDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AScenarioRolesDeclarationScenarioElement(
            cloneNode(this._rolesDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAScenarioRolesDeclarationScenarioElement(this);
    }

    public PRolesDeclaration getRolesDeclaration()
    {
        return this._rolesDeclaration_;
    }

    public void setRolesDeclaration(PRolesDeclaration node)
    {
        if(this._rolesDeclaration_ != null)
        {
            this._rolesDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rolesDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rolesDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rolesDeclaration_ == child)
        {
            this._rolesDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rolesDeclaration_ == oldChild)
        {
            setRolesDeclaration((PRolesDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
