/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleStepScenarioElement extends PScenarioElement
{
    private PSimpleStepDeclaration _simpleStepDeclaration_;

    public ASimpleStepScenarioElement()
    {
        // Constructor
    }

    public ASimpleStepScenarioElement(
        @SuppressWarnings("hiding") PSimpleStepDeclaration _simpleStepDeclaration_)
    {
        // Constructor
        setSimpleStepDeclaration(_simpleStepDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleStepScenarioElement(
            cloneNode(this._simpleStepDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleStepScenarioElement(this);
    }

    public PSimpleStepDeclaration getSimpleStepDeclaration()
    {
        return this._simpleStepDeclaration_;
    }

    public void setSimpleStepDeclaration(PSimpleStepDeclaration node)
    {
        if(this._simpleStepDeclaration_ != null)
        {
            this._simpleStepDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simpleStepDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simpleStepDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simpleStepDeclaration_ == child)
        {
            this._simpleStepDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simpleStepDeclaration_ == oldChild)
        {
            setSimpleStepDeclaration((PSimpleStepDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
