/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleScenarioDeclarationScenarioDeclaration extends PScenarioDeclaration
{
    private PSimpleScenarioDeclaration _simpleScenarioDeclaration_;

    public ASimpleScenarioDeclarationScenarioDeclaration()
    {
        // Constructor
    }

    public ASimpleScenarioDeclarationScenarioDeclaration(
        @SuppressWarnings("hiding") PSimpleScenarioDeclaration _simpleScenarioDeclaration_)
    {
        // Constructor
        setSimpleScenarioDeclaration(_simpleScenarioDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleScenarioDeclarationScenarioDeclaration(
            cloneNode(this._simpleScenarioDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleScenarioDeclarationScenarioDeclaration(this);
    }

    public PSimpleScenarioDeclaration getSimpleScenarioDeclaration()
    {
        return this._simpleScenarioDeclaration_;
    }

    public void setSimpleScenarioDeclaration(PSimpleScenarioDeclaration node)
    {
        if(this._simpleScenarioDeclaration_ != null)
        {
            this._simpleScenarioDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simpleScenarioDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simpleScenarioDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simpleScenarioDeclaration_ == child)
        {
            this._simpleScenarioDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simpleScenarioDeclaration_ == oldChild)
        {
            setSimpleScenarioDeclaration((PSimpleScenarioDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
