/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleShadowScenarioElement extends PScenarioElement
{
    private PSimpleShadowStepDeclaration _simpleShadowStepDeclaration_;

    public ASimpleShadowScenarioElement()
    {
        // Constructor
    }

    public ASimpleShadowScenarioElement(
        @SuppressWarnings("hiding") PSimpleShadowStepDeclaration _simpleShadowStepDeclaration_)
    {
        // Constructor
        setSimpleShadowStepDeclaration(_simpleShadowStepDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleShadowScenarioElement(
            cloneNode(this._simpleShadowStepDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleShadowScenarioElement(this);
    }

    public PSimpleShadowStepDeclaration getSimpleShadowStepDeclaration()
    {
        return this._simpleShadowStepDeclaration_;
    }

    public void setSimpleShadowStepDeclaration(PSimpleShadowStepDeclaration node)
    {
        if(this._simpleShadowStepDeclaration_ != null)
        {
            this._simpleShadowStepDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simpleShadowStepDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simpleShadowStepDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simpleShadowStepDeclaration_ == child)
        {
            this._simpleShadowStepDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simpleShadowStepDeclaration_ == oldChild)
        {
            setSimpleShadowStepDeclaration((PSimpleShadowStepDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
