/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ATextIvarStepType extends PIvarStepType
{
    private TTextTypeKeyword _textTypeKeyword_;

    public ATextIvarStepType()
    {
        // Constructor
    }

    public ATextIvarStepType(
        @SuppressWarnings("hiding") TTextTypeKeyword _textTypeKeyword_)
    {
        // Constructor
        setTextTypeKeyword(_textTypeKeyword_);

    }

    @Override
    public Object clone()
    {
        return new ATextIvarStepType(
            cloneNode(this._textTypeKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATextIvarStepType(this);
    }

    public TTextTypeKeyword getTextTypeKeyword()
    {
        return this._textTypeKeyword_;
    }

    public void setTextTypeKeyword(TTextTypeKeyword node)
    {
        if(this._textTypeKeyword_ != null)
        {
            this._textTypeKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._textTypeKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._textTypeKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._textTypeKeyword_ == child)
        {
            this._textTypeKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._textTypeKeyword_ == oldChild)
        {
            setTextTypeKeyword((TTextTypeKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
