/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ATimeIvarStepType extends PIvarStepType
{
    private TTimeTypeKeyword _timeTypeKeyword_;

    public ATimeIvarStepType()
    {
        // Constructor
    }

    public ATimeIvarStepType(
        @SuppressWarnings("hiding") TTimeTypeKeyword _timeTypeKeyword_)
    {
        // Constructor
        setTimeTypeKeyword(_timeTypeKeyword_);

    }

    @Override
    public Object clone()
    {
        return new ATimeIvarStepType(
            cloneNode(this._timeTypeKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATimeIvarStepType(this);
    }

    public TTimeTypeKeyword getTimeTypeKeyword()
    {
        return this._timeTypeKeyword_;
    }

    public void setTimeTypeKeyword(TTimeTypeKeyword node)
    {
        if(this._timeTypeKeyword_ != null)
        {
            this._timeTypeKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._timeTypeKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._timeTypeKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._timeTypeKeyword_ == child)
        {
            this._timeTypeKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._timeTypeKeyword_ == oldChild)
        {
            setTimeTypeKeyword((TTimeTypeKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
