/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ATypeImportDeclaration extends PImportDeclaration
{
    private PTypeImportStarDeclaration _typeImportStarDeclaration_;

    public ATypeImportDeclaration()
    {
        // Constructor
    }

    public ATypeImportDeclaration(
        @SuppressWarnings("hiding") PTypeImportStarDeclaration _typeImportStarDeclaration_)
    {
        // Constructor
        setTypeImportStarDeclaration(_typeImportStarDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new ATypeImportDeclaration(
            cloneNode(this._typeImportStarDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeImportDeclaration(this);
    }

    public PTypeImportStarDeclaration getTypeImportStarDeclaration()
    {
        return this._typeImportStarDeclaration_;
    }

    public void setTypeImportStarDeclaration(PTypeImportStarDeclaration node)
    {
        if(this._typeImportStarDeclaration_ != null)
        {
            this._typeImportStarDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeImportStarDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typeImportStarDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typeImportStarDeclaration_ == child)
        {
            this._typeImportStarDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._typeImportStarDeclaration_ == oldChild)
        {
            setTypeImportStarDeclaration((PTypeImportStarDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
