/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TAmountTypeKeyword extends Token
{
    public TAmountTypeKeyword()
    {
        super.setText("Amount");
    }

    public TAmountTypeKeyword(int line, int pos)
    {
        super.setText("Amount");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAmountTypeKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAmountTypeKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAmountTypeKeyword text.");
    }
}
