/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TApplicationKeyword extends Token
{
    public TApplicationKeyword()
    {
        super.setText("application");
    }

    public TApplicationKeyword(int line, int pos)
    {
        super.setText("application");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TApplicationKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTApplicationKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TApplicationKeyword text.");
    }
}
