/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TCrudDeleteKeyword extends Token
{
    public TCrudDeleteKeyword()
    {
        super.setText("delete");
    }

    public TCrudDeleteKeyword(int line, int pos)
    {
        super.setText("delete");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCrudDeleteKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCrudDeleteKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCrudDeleteKeyword text.");
    }
}
