/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TDataKeyword extends Token
{
    public TDataKeyword()
    {
        super.setText("data");
    }

    public TDataKeyword(int line, int pos)
    {
        super.setText("data");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDataKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDataKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDataKeyword text.");
    }
}
