/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TDateTypeKeyword extends Token
{
    public TDateTypeKeyword()
    {
        super.setText("Date");
    }

    public TDateTypeKeyword(int line, int pos)
    {
        super.setText("Date");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDateTypeKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDateTypeKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDateTypeKeyword text.");
    }
}
