/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TFileTypeKeyword extends Token
{
    public TFileTypeKeyword()
    {
        super.setText("File");
    }

    public TFileTypeKeyword(int line, int pos)
    {
        super.setText("File");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFileTypeKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFileTypeKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFileTypeKeyword text.");
    }
}
