/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TFormatedtextTypeKeyword extends Token
{
    public TFormatedtextTypeKeyword()
    {
        super.setText("Formatedtext");
    }

    public TFormatedtextTypeKeyword(int line, int pos)
    {
        super.setText("Formatedtext");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFormatedtextTypeKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFormatedtextTypeKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFormatedtextTypeKeyword text.");
    }
}
