/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TImageTypeKeyword extends Token
{
    public TImageTypeKeyword()
    {
        super.setText("Image");
    }

    public TImageTypeKeyword(int line, int pos)
    {
        super.setText("Image");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TImageTypeKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTImageTypeKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TImageTypeKeyword text.");
    }
}
