/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TMultitextTypeKeyword extends Token
{
    public TMultitextTypeKeyword()
    {
        super.setText("Multitext");
    }

    public TMultitextTypeKeyword(int line, int pos)
    {
        super.setText("Multitext");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMultitextTypeKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMultitextTypeKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMultitextTypeKeyword text.");
    }
}
