/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TPasswordTypeKeyword extends Token
{
    public TPasswordTypeKeyword()
    {
        super.setText("Password");
    }

    public TPasswordTypeKeyword(int line, int pos)
    {
        super.setText("Password");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPasswordTypeKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPasswordTypeKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPasswordTypeKeyword text.");
    }
}
