/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TRolesKeyword extends Token
{
    public TRolesKeyword()
    {
        super.setText("roles");
    }

    public TRolesKeyword(int line, int pos)
    {
        super.setText("roles");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRolesKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRolesKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRolesKeyword text.");
    }
}
