/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TScenarioKeyword extends Token
{
    public TScenarioKeyword()
    {
        super.setText("scenario");
    }

    public TScenarioKeyword(int line, int pos)
    {
        super.setText("scenario");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TScenarioKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTScenarioKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TScenarioKeyword text.");
    }
}
