/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TTextTypeKeyword extends Token
{
    public TTextTypeKeyword()
    {
        super.setText("Text");
    }

    public TTextTypeKeyword(int line, int pos)
    {
        super.setText("Text");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTextTypeKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTextTypeKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTextTypeKeyword text.");
    }
}
