/* This file was generated by SableCC (http://www.sablecc.org/). */

package ivar.grammar.node;

import ivar.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TTimeTypeKeyword extends Token
{
    public TTimeTypeKeyword()
    {
        super.setText("Time");
    }

    public TTimeTypeKeyword(int line, int pos)
    {
        super.setText("Time");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTimeTypeKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTimeTypeKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTimeTypeKeyword text.");
    }
}
