/*
   Copyright (c) 2004-2020, Jean-Baptiste BRIAUD. All Rights Reserved.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License
 */
package ivar.metamodel;

public class ReservedKeywords {

    public static final String[] specReservedKeywords = new String[]{"data", "dataset"};
    public static final String[] SQLReservedKeywords = new String[]{"ADD", "ALL", "ALTER", "AND", "ANY", "AS", "ASC", "AUTHORIZATION", "BACKUP", "BEGIN", "BETWEEN", "BREAK", "BROWSE", "BULK", "BY", "CASCADE", "CASE", "CHECK", "CHECKPOINT", "CLOSE", "CLUSTERED", "COALESCE", "COLLATE", "COLUMN", "COMMIT", "COMPUTE", "CONSTRAINT", "CONTAINS", "CONTAINSTABLE", "CONTINUE", "CONVERT", "CREATE", "CROSS", "CURRENT", "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_USER", "CURSOR", "DATABASE", "DBCC", "DEALLOCATE", "DECLARE", "DEFAULT", "DELETE", "DENY", "DESC", "DISK", "DISTINCT", "DISTRIBUTED", "DOUBLE", "DROP", "DUMMY", "DUMP", "ELSE", "END", "ERRLVL", "ESCAPE", "EXCEPT", "EXEC", "EXECUTE", "EXISTS", "EXIT", "FETCH", "FILE", "FILLFACTOR", "FOR", "FOREIGN", "FREETEXT", "FREETEXTTABLE", "FROM", "FULL", "FUNCTION", "GOTO", "GRANT", "GROUP", "HAVING", "HOLDLOCK", "IDENTITY", "IDENTITY_INSERT", "IDENTITYCOL", "IF", "IN", "INDEX", "INNER", "INSERT", "INTERSECT", "INTO", "IS", "JOIN", "KEY", "KILL", "LEFT", "LIKE", "LINENO", "LOAD", "NATIONAL", "NOCHECK", "NONCLUSTERED", "NOT", "NULL", "NULLIF", "OF", "OFF", "OFFSETS", "ON", "OPEN", "OPENDATASOURCE", "OPENQUERY", "OPENROWSET", "OPENXML", "OPTION", "OR", "ORDER", "OUTER", "OVER", "PERCENT", "PLAN", "PRECISION", "PRIMARY", "PRINT", "PROC", "PROCEDURE", "PUBLIC", "RAISERROR", "READ", "READTEXT", "RECONFIGURE", "REFERENCES", "REPLICATION", "RESTORE", "RESTRICT", "RETURN", "REVOKE", "RIGHT", "ROLLBACK", "ROWCOUNT", "ROWGUIDCOL", "RULE", "SAVE", "SCHEMA", "SELECT", "SESSION_USER", "SET", "SETUSER", "SHUTDOWN", "SOME", "STATISTICS", "SYSTEM_USER", "TABLE", "TEXTSIZE", "THEN", "TO", "TOP", "TRAN", "TRANSACTION", "TRIGGER", "TRUNCATE", "TSEQUAL", "UNION", "UNIQUE", "UPDATE", "UPDATETEXT", "USE", "USER", "VALUES", "VARYING", "VIEW", "WAITFOR", "WHEN", "WHERE", "WHILE", "WITH", "WRITETEXT"};
    public static final String[] PLSQL_1_ReservedKeywords = new String[]{"ALL", "ALTER", "AND", "ANY", "ARRAY", "ARROW", "AS", "ASC", "AT", "BEGIN", "CASE", "DECIMAL", "ELSE", "FETCH", "GOTO", "HAVING", "IDENTIFIED", "LIKE", "MINUS", "NOCOMPRESS", "OF", "PRIOR", "RANGE", "SELECT", "TABAUTH", "UNION", "VALUES", "WHEN", "IF", "LOCK", "MODE", "NOT", "ON", "PROCEDURE", "RECORD", "SHARE", "TABLE", "UNIQUE", "VIEW", "WHERE", "BETWEEN", "CHECK", "DECLARE", "END", "FORM", "GRANT", "CLUSTERS", "CLUSTER", "COLAUTH", "COLUMNS", "COMPRESS", "CONNECT", "CRASH", "CREATE", "CURRENT", "DEFAULT", "EXCEPTION", "FOR", "GROUP", "IN", "NOWAIT", "OPTION", "PUBLIC", "RESOURCE", "SIZE", "THEN", "UPDATE", "VIEWS", "WITH", "IS", "INTO", "BY", "DELETE", "EXCLUSIVE", "FROM", "INDEXES", "NULL", "OR", "REVOKE", "SQL", "TO", "USE", "DESC", "EXISTS", "INDEX", "ORDER", "START", "TYPE", "DISTINCT", "INSERT", "OVERLAPS", "SUBTYPE", "DROP", "INTERSECT"};
    public static final String[] PLSQL_2_ReservedKeywords = new String[]{"BFILE_BASE", "DANGLING", "ELEMENT", "FINAL", "GENERAL", "HASH", "IMMEDIATE", "JAVA", "LANGUAGE", "MAP", "OBJECT", "PACKAGE", "RAISE", "SAMPLE", "TDO", "UB1", "VALIST", "WHILE", "YEAR", "ZONE", "ADD", "BINARY", "CALL", "DATA", "ELSIF", "FIXED", "HEAP", "INCLUDING", "LARGE", "MAX", "NAN", "OCICOLL", "PARALLEL_ENABLE", "RANGE", "SAVE", "THE", "UB2", "VALUE", "WORK", "AGENT", "BLOB_BASE", "CALLING", "DATE", "EMPTY", "FLOAT", "HIDDEN", "INDICATOR", "LEADING", "MAXLEN", "NATIONAL", "OCIDATETIME", "PARAMETER", "RAW", "SAVEPOINT", "TIME", "UB4", "VARIABLE", "WRAPPED", "AGGREGATE", "BLOCK", "CASCADE", "DATE_BASE", "ESCAPE", "FORALL", "HOUR", "INDICES", "LENGTH", "MEMBER", "NATIVE", "OCIDATE", "PARAMETERS", "READ", "SB1", "TIMESTAMP", "UNDER", "VARIANCE", "WRITE", "ARRAY", "BODY", "CHAR", "DAY", "EXCEPT", "FORCE", "INFINITE", "LEVEL", "MERGE", "NCHAR", "OCIDURATION", "PARTITION", "RECORD", "SB2", "TIMEZONE_ABBR", "UNSIGNED", "VARRAY", "ATTRIBUTE", "BOTH", "CHAR_BASE", "DEFINE", "EXCEPTIONS", "FUNCTION", "INSTANTIABLE", "LIBRARY", "MIN", "NEW", "OCIINTERVAL", "PASCAL", "REF", "SB4", "TIMEZONE_HOUR", "UNTRUSTED", "VARYING", "AUTHID", "BOUND", "CHARACTER", "DETERMINISTIC", "EXECUTE", "INT", "LIKE2", "MINUTE", "NOCOPY", "OCILOBLOCATOR", "PIPE", "REFERENCE", "SECOND", "TIMEZONE_MINUTE", "USE", "VOID", "CHARSETFORM", "CHARSETID", "CHARSET", "CLOB_BASE", "CLOSE", "COLLECT", "COMMENT", "COMMIT", "COMMITTED", "COMPILED", "CONSTANT", "CONSTRUCTOR", "CONTEXT", "CONVERT", "COUNT", "CURSOR", "CUSTOMDATUM", "AVG", "BULK", "DOUBLE", "EXIT", "INTERFACE", "LIKE4", "MOD", "NUMBER_BASE", "OCINUMBER", "PIPELINED", "REM", "SEGMENT", "TIMEZONE_REGION", "USING", "BYTE", "DURATION", "EXTERNAL", "INTERVAL", "LIKEC", "MODIFY", "OCIRAW", "PRAGMA", "REMAINDER", "SELF", "TRAILING", "INVALIDATE", "LIMIT", "MONTH", "OCIREFCURSOR", "PRECISION", "RENAME", "SEPARATE", "TRANSAC", "ISOLATION", "LIMITED", "MULTISET", "OCIREF", "PRIVATE", "RESULT", "SEQUENCE", "TRANSACTIONAL", "SQLCODE", "OPERATOR", "LOCAL", "OCIROWID", "RETURN", "SERIALIZABLE", "TRUSTED", "LOOP", "OCITYPE", "REVERSE", "SHORT", "ONLY", "ROLLBACK", "SIZE_T", "OPAQUE", "ROW", "SOME", "SPARSE", "OPEN", "SQLDATA", "SQLNAME", "SQLSTATE", "STANDARD", "STATIC", "ORACLE", "ORADATA", "ORGANIZATION", "ORLANY", "ORLVARY", "OTHERS", "OUT", "OVERRIDING", "LONG", "OCISTRING", "RETURNING", "SET", "TYPE", "STRUCT", "STYLE", "SUBMULTISET", "SUBPARTITION", "SUBSTITUTABLE", "SUBTYPE", "SUM", "SYNONYM", "STDDEV", "STORED", "STRING"};
    public static final String[] ODBC_ReservedKeywords = new String[]{"ABSOLUTE", "ACTION", "ADA", "ADD", "ALL", "ALLOCATE", "ALTER", "AND", "ANY", "ARE", "AS", "ASC", "ASSERTION", "AT", "AUTHORIZATION", "AVG", "BEGIN", "BETWEEN", "BIT", "BIT_LENGTH", "BOTH", "BY", "CASCADE", "CASCADED", "CASE", "CAST", "CATALOG", "CHAR", "CHAR_LENGTH", "CHARACTER", "CHARACTER_LENGTH", "CHECK", "CLOSE", "COALESCE", "COLLATE", "COLLATION", "COLUMN", "COMMIT", "CONNECT", "CONNECTION", "CONSTRAINT", "CONSTRAINTS", "CONTINUE", "CONVERT", "CORRESPONDING", "COUNT", "CREATE", "CROSS", "CURRENT", "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_USER", "CURSOR", "DATE", "DAY", "DEALLOCATE", "DEC", "DECIMAL", "DECLARE", "DEFAULT", "DEFERRABLE", "DEFERRED", "DELETE", "DESC", "DESCRIBE", "DESCRIPTOR", "DIAGNOSTICS", "DISCONNECT", "DISTINCT", "DOMAIN", "DOUBLE", "DROP", "ELSE", "END", "END-EXEC", "ESCAPE", "EXCEPT", "EXCEPTION", "EXEC", "EXECUTE", "EXISTS", "EXTERNAL", "EXTRACT", "FALSE", "FETCH", "FIRST", "FLOAT", "FOR", "FOREIGN", "FORTRAN", "FOUND", "FROM", "FULL", "GET", "GLOBAL", "GO", "GOTO", "GRANT", "GROUP", "HAVING", "HOUR", "IDENTITY", "IMMEDIATE", "IN", "INCLUDE", "INDEX", "INDICATOR", "INITIALLY", "INNER", "INPUT", "INSENSITIVE", "INSERT", "INT", "INTEGER", "INTERSECT", "INTERVAL", "INTO", "IS", "ISOLATION", "JOIN", "KEY", "LANGUAGE", "LAST", "LEADING", "LEFT", "LEVEL", "LIKE", "LOCAL", "LOWER", "MATCH", "MAX", "MIN", "MINUTE", "MODULE", "MONTH", "NATIONAL", "NATURAL", "NCHAR", "NEXT", "NO", "NONE", "NOT", "NULL", "NULLIF", "NUMERIC", "OCTET_LENGTH", "OF", "ON", "ONLY", "OPEN", "OPTION", "OR", "ORDER", "OUTER", "OUTPUT", "OVERLAPS", "PAD", "PARTIAL", "PASCAL", "POSITION", "PRECISION", "PREPARE", "PRESERVE", "PRIMARY", "PRIOR", "PRIVILEGES", "PROCEDURE", "PUBLIC", "READ", "REAL", "REFERENCES", "RELATIVE", "RESTRICT", "REVOKE", "RIGHT", "ROLLBACK", "ROWS", "SCHEMA", "SCROLL", "SECOND", "SECTION", "SELECT", "SESSION", "SESSION_USER", "SET", "SIZE", "SMALLINT", "SOME", "SPACE", "SQL", "SQLCA", "SQLCODE", "SQLERROR", "SQLSTATE", "SQLWARNING", "SUBSTRING", "SUM", "SYSTEM_USER", "TABLE", "TEMPORARY", "THEN", "TIME", "TIMESTAMP", "TIMEZONE_HOUR", "TIMEZONE_MINUTE", "TO", "TRAILING", "TRANSACTION", "TRANSLATE", "TRANSLATION", "TRIM", "TRUE", "UNION", "UNIQUE", "UNKNOWN", "UPDATE", "UPPER", "USAGE", "USER", "USING", "VALUE", "VALUES", "VARCHAR", "VARYING", "VIEW", "WHEN", "WHENEVER", "WHERE", "WITH", "WORK", "WRITE", "YEAR", "ZONE"};
    public static final String[] SQL_FUTURE_ReservedKeywords = new String[]{"ABSOLUTE", "ACTION", "ADMIN", "AFTER", "AGGREGATE", "ALIAS", "ALLOCATE", "ARE", "ARRAY", "ASSERTION", "AT", "BEFORE", "BINARY", "BIT", "BLOB", "BOOLEAN", "BOTH", "BREADTH", "CALL", "CASCADED", "CAST", "CATALOG", "CHAR", "CHARACTER", "CLASS", "CLOB", "COLLATION", "COMPLETION", "CONNECT", "CONNECTION", "CONSTRAINTS", "CONSTRUCTOR", "CORRESPONDING", "CUBE", "CURRENT_PATH", "CURRENT_ROLE", "CYCLE", "DATA", "DATE", "DAY", "DEC", "DECIMAL", "DEFERRABLE", "DEFERRED", "DEPTH", "DEREF", "DESCRIBE", "DESCRIPTOR", "DESTROY", "DESTRUCTOR", "DETERMINISTIC", "DICTIONARY", "DIAGNOSTICS", "DISCONNECT", "DOMAIN", "DYNAMIC", "EACH", "END-EXEC", "EQUALS", "EVERY", "EXCEPTION", "EXTERNAL", "FALSE", "FIRST", "FLOAT", "FOUND", "FREE", "GENERAL", "GET", "GLOBAL", "GO", "GROUPING", "HOST", "HOUR", "IGNORE", "IMMEDIATE", "INDICATOR", "INITIALIZE", "INITIALLY", "INOUT", "INPUT", "INT", "INTEGER", "INTERVAL", "ISOLATION", "ITERATE", "LANGUAGE", "LARGE", "LAST", "LATERAL", "LEADING", "LESS", "LEVEL", "LIMIT", "LOCAL", "LOCALTIME", "LOCALTIMESTAMP", "LOCATOR", "MAP", "MATCH", "MINUTE", "MODIFIES", "MODIFY", "MODULE", "MONTH", "NATURAL", "NCHAR", "NCLOB", "NEW", "NEXT", "NO", "NONE", "NUMERIC", "OBJECT", "OLD", "ONLY", "OPERATION", "ORDINALITY", "OUT", "OUTPUT", "PAD", "PARAMETER", "PARAMETERS", "PARTIAL", "PATH", "POSTFIX", "PREFIX", "PREORDER", "PREPARE", "PRESERVE", "PRIOR", "PRIVILEGES", "READS", "REAL", "RECURSIVE", "REF", "REFERENCING", "RELATIVE", "RESULT", "RETURNS", "ROLE", "ROLLUP", "ROUTINE", "ROW", "ROWS", "SAVEPOINT", "SCROLL", "SCOPE", "SEARCH", "SECOND", "SECTION", "SEQUENCE", "SESSION", "SETS", "SIZE", "SMALLINT", "SPACE", "SPECIFIC", "SPECIFICTYPE", "SQL", "SQLEXCEPTION", "SQLSTATE", "SQLWARNING", "START", "STATE", "STATEMENT", "STATIC", "STRUCTURE", "TEMPORARY", "TERMINATE", "THAN", "TIME", "TIMESTAMP", "TIMEZONE_HOUR", "TIMEZONE_MINUTE", "TRAILING", "TRANSLATION", "TREAT", "TRUE", "UNDER", "UNKNOWN", "UNNEST", "USAGE", "USING", "VALUE", "VARCHAR", "VARIABLE", "WHENEVER", "WITHOUT", "WORK", "WRITE", "YEAR", "ZONE"};
    public static final String[] JAVA_ReservedKeywords = new String[]{"abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class", "const", "continue", "default", "do", "double", "else", "enum", "extends", "final", "finally", "float", "for", "goto", "if", "implements", "import", "instanceof", "int", "interface", "long", "native", "new", "package", "private", "protected", "public", "return", "short", "static", "strictfp", "super", "switch", "synchronized", "this", "throw", "throws", "transient", "try", "void", "volatile", "while", "FutureKeywords"};
    public static final String[] JAVASCRIPT_ReservedKeywords = new String[]{"abstract", "boolean", "break", "byte", "case", "catch", "char", "class", "const", "continue", "debugger", "default", "delete", "do", "double", "else", "enum", "export", "extends", "FALSE", "final", "finally", "float", "for", "function", "goto", "if", "implements", "import", "in", "instanceof", "int", "interface", "long", "native", "new", "null", "package", "private", "protected", "public", "return", "short", "static", "super", "switch", "synchronized", "this", "throw", "throws", "transient", "TRUE", "try", "typeof", "var", "void", "volatile", "while", "with"};
    public static final String[][] SQL_RESERVED_KEYWORDS = new String[][]{SQLReservedKeywords, PLSQL_1_ReservedKeywords, PLSQL_2_ReservedKeywords, ODBC_ReservedKeywords, SQL_FUTURE_ReservedKeywords};
    public static final String[][] LANGUAGES_RESERVED_KEYWORDS = new String[][]{JAVA_ReservedKeywords, JAVASCRIPT_ReservedKeywords};
}
